# Generated by Django 6.0.2 on 2026-02-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receipts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receiptscan",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("confirmed", "Confirmed"),
                    ("failed", "Failed"),
                ],
                default="processing",
                max_length=20,
            ),
        ),
    ]
