# Generated by Django 5.1.15 on 2026-02-24 18:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("external_id", models.CharField(blank=True, max_length=100, null=True)),
                ("source", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("instructions", models.JSONField(default=list)),
                ("ingredients_json", models.JSONField(default=list)),
                ("prep_time_minutes", models.IntegerField(blank=True, null=True)),
                ("cook_time_minutes", models.IntegerField(blank=True, null=True)),
                ("servings", models.SmallIntegerField(blank=True, null=True)),
                ("difficulty", models.CharField(blank=True, max_length=20, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("nutrition", models.JSONField(blank=True, null=True)),
                ("source_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "recipes",
                "constraints": [
                    models.UniqueConstraint(fields=("source", "external_id"), name="unique_recipe_source_external_id")
                ],
            },
        ),
        migrations.CreateModel(
            name="CookingLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("cooked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cooking_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cooking_logs", to="recipes.recipe"
                    ),
                ),
            ],
            options={
                "db_table": "cooking_log",
                "ordering": ["-cooked_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedRecipe",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="saved_by", to="recipes.recipe"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_recipes",
                "constraints": [models.UniqueConstraint(fields=("user", "recipe"), name="unique_saved_recipe")],
            },
        ),
    ]
