# Generated by Django 6.0.2 on 2026-03-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="feedback_consent",
            field=models.BooleanField(default=False, help_text="User has opted in to being contacted for feedback"),
        ),
        migrations.AddField(
            model_name="user",
            name="feedback_consent_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="When feedback consent was last changed (GDPR audit trail)", null=True
            ),
        ),
    ]
