# Generated by Django 5.1.15 on 2026-02-24 18:51

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
        ('receipts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('added_date', models.DateField(default=datetime.date.today)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(choices=[('receipt_scan', 'Receipt Scan'), ('manual', 'Manual')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('expired', 'Expired'), ('used_up', 'Used Up')], default='available', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pantry_items', to='ingredients.ingredient')),
                ('receipt_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pantry_items', to='receipts.receiptscan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pantry_items',
                'ordering': ['expiry_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'available')), fields=('user', 'ingredient'), name='unique_available_pantry_item')],
            },
        ),
    ]
