# Generated by Django 6.0.2 on 2026-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pantry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pantryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("expired", "Expired"),
                    ("used_up", "Used Up"),
                    ("to_buy", "To Buy"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
